#-Basic info----------------------------------------------------------------------------------------
name: min_read_check
version: 2.0.5
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: size_check
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: recommended
  description: >
    Checks that there's a minimum number of reads after trimming to run.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-min_read_check:2.0.5"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  min_num_reads: 10000
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  adapters_fasta: "/bifrost_resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      datafiles:
        paired_reads:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    properties:
      size_check:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
  sample_component:
    summary:
      has_min_num_of_reads:  # Boolean
    results:
      min_read_check/data_yaml: {}
#---------------------------------------------------------------------------------------------------
