version: '3.8'
services:
  python:
    build:
      context: .
      args:
        BUILD_ENV: dev
    env_file:
      - .secrets/mongodb_dev_key.env
  python-tests:
    build:
      context: .
      args:
        BUILD_ENV: dev
    env_file:
      - .secrets/mongodb_dev_key.env
    working_dir: /bifrost_min_read_check/
    volumes:
      - ./bifrost_min_read_check:/bifrost_min_read_check/bifrost_min_read_check
      - ./tests:/bifrost_min_read_check/tests
      - ../../lib/bifrostlib:/bifrostlib
      # - ../bifrost_run_launcher/bifrost_run_launcher:/bifrost_run_launcher/bifrost_run_launcher
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="/bifrost_min_read_check" -- pytest --verbose
    depends_on:
      - python