#-Basic info----------------------------------------------------------------------------------------
display_name: min_read_check
name: min_read_check__unspecified__unspecified
version:
  code: unspecified
  resource: unspecified
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: recommended
  description: >
    Checks that there's a minimum number of reads after trimming to run.
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_min_read_check:unspecified__unspecified
# None
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [size_check]
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  min_num_reads: 10000
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  adapters_fasta: "resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      paired_reads:
        summary:
          data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    properties:
      size_check:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
  sample_component:
    summary:
      has_min_num_of_reads:  # Boolean
    results:
      min_read_check/data_yaml: {}
#---------------------------------------------------------------------------------------------------
